# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: BTD

on:
  push:
    branches: [ "master" ]

jobs:

  strategy:
    matrix:
      node-version: [18.x]
      # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

  setup:
    name: Setup
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      uses: actions/setup-node@v3
      with:
        cache: 'npm'
    - run: npm ci

  build:
    name: Build
    runs-on: self-hosted
    steps:
    - run: npm run build

  test:
    name: Test
    runs-on: self-hosted
    steps:
    - run: npm run test

  deploy:
    name: Deploy
    runs-on: self-hosted
    steps:
    - run: npm run deploy
