# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI/CD

on:
  push:
    branches: [ master ]

jobs: 

  build:
    name: Deploy
    runs-on: self-hosted

    steps:
    - uses: dcodeIO/setup-node-nvm@master
      with:
        node-version: 18
    - run: npm ci
    - run: npm run test
    - run: npm run build
    - run: npm run deploy
    - run: npm run cleanup
